<?binding.jca PermTable_db.jca?>
<wsdl:definitions name="PermTable" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Misc/CarrierToMisc/PermTable" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Misc/CarrierToMisc/PermTable" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/PermTable">
    <plt:partnerLinkType name="PermTable_plt">
        <plt:role name="PermTable_role">
            <plt:portType name="tns:PermTable_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/PermTable" schemaLocation="xsd/PermTable_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="PermTableSelect_inputParameters">
        <wsdl:part name="PermTableSelect_inputParameters" element="top:PermTableSelect_vchrNbrInputParameters"/>
    </wsdl:message>
    <wsdl:message name="InvcMtchExcptCollection_msg">
        <wsdl:part name="InvcMtchExcptCollection" element="top:InvcMtchExcptCollection"/>
    </wsdl:message>
    <wsdl:portType name="PermTable_ptt">
        <wsdl:operation name="PermTableSelect">
            <wsdl:input message="tns:PermTableSelect_inputParameters"/>
            <wsdl:output message="tns:InvcMtchExcptCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
