<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../US122M_PSV_File.wsdl"/>
      <rootElement name="US122M_Root-Element" namespace="http://TargetNamespace.com/US122M_PSV_File"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../US122M.wsdl"/>
      <rootElement name="SlsTaxCltRptCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/US122M"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [TUE DEC 23 22:45:35 EST 2014]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/US122M"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:imp1="http://TargetNamespace.com/US122M_PSV_File"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/Misc/Misc/US122M"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/file/Misc/Misc/US122M_PSV_File"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl pc plt wsdl imp1 jca xsd tns top ns0 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <top:SlsTaxCltRptCollection>
      <xsl:for-each select="/imp1:US122M_Root-Element/imp1:US122M">
        <top:SlsTaxCltRpt>
          <top:fileCrtDt>
            <xsl:value-of select="imp1:rptdt"/>
          </top:fileCrtDt>
          <top:strNbr>
            <xsl:value-of select="imp1:strnbr"/>
          </top:strNbr>
          <top:strStCd>
            <xsl:value-of select="imp1:strst"/>
          </top:strStCd>
          <top:custCityNm>
            <xsl:value-of select="imp1:cstmrcty"/>
          </top:custCityNm>
          <top:custCntyNm>
            <xsl:value-of select="imp1:cstmrcnty"/>
          </top:custCntyNm>
          <top:custStCd>
            <xsl:value-of select="imp1:cstmrst"/>
          </top:custStCd>
          <top:custPstlCd>
            <xsl:value-of select="imp1:cstmrzip"/>
          </top:custPstlCd>
          <top:custOrdId>
            <xsl:value-of select="imp1:cstmrordnbr"/>
          </top:custOrdId>
          <top:slsDt>
            <xsl:value-of select="imp1:salesdt"/>
          </top:slsDt>
          <top:cordSrcTypCd>
            <xsl:value-of select="imp1:origcd"/>
          </top:cordSrcTypCd>
          <top:slsTaxAmt>
            <xsl:value-of select="imp1:txamt"/>
          </top:slsTaxAmt>
          <top:strTaxJursdInd>
            <xsl:value-of select="imp1:txnortrn"/>
          </top:strTaxJursdInd>
        </top:SlsTaxCltRpt>
      </xsl:for-each>
    </top:SlsTaxCltRptCollection>
  </xsl:template>
</xsl:stylesheet>
