<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../US122M_PSV_File.wsdl"/>
      <rootElement name="US122M_Root-Element" namespace="http://TargetNamespace.com/US122M_PSV_File"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../US122M_PSV_File.wsdl"/>
      <rootElement name="US122M_Root-Element" namespace="http://TargetNamespace.com/US122M_PSV_File"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [TUE DEC 23 23:01:17 EST 2014]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:imp1="http://TargetNamespace.com/US122M_PSV_File"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/file/Misc/Misc/US122M_PSV_File"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl pc plt wsdl imp1 jca xsd tns xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <imp1:US122M_Root-Element>
      <xsl:for-each select="/imp1:US122M_Root-Element/imp1:US122M">
        <imp1:US122M>
          <imp1:imagefilename>
            <xsl:value-of select="imp1:imagefilename"/>
          </imp1:imagefilename>
          <imp1:rptdt>
            <xsl:value-of select="imp1:rptdt"/>
          </imp1:rptdt>
          <imp1:strst>
            <xsl:value-of select="imp1:strst"/>
          </imp1:strst>
          <imp1:strnbr>
            <xsl:value-of select="imp1:strnbr"/>
          </imp1:strnbr>
          <imp1:cstmrst>
            <xsl:value-of select="imp1:cstmrst"/>
          </imp1:cstmrst>
          <imp1:cstmrcnty>
            <xsl:value-of select="imp1:cstmrcnty"/>
          </imp1:cstmrcnty>
          <imp1:cstmrcty>
            <xsl:value-of select="imp1:cstmrcty"/>
          </imp1:cstmrcty>
          <imp1:cstmrzip>
            <xsl:value-of select="imp1:cstmrzip"/>
          </imp1:cstmrzip>
          <imp1:cstmrordnbr>
            <xsl:value-of select="imp1:cstmrordnbr"/>
          </imp1:cstmrordnbr>
          <imp1:salesdt>
            <xsl:value-of select="imp1:salesdt"/>
          </imp1:salesdt>
          <imp1:origcd>
            <xsl:value-of select="imp1:origcd"/>
          </imp1:origcd>
          <imp1:txamt>
            <xsl:value-of select="imp1:txamt"/>
          </imp1:txamt>
          <imp1:txnortrn>
            <xsl:value-of select="imp1:txnortrn"/>
          </imp1:txnortrn>
        </imp1:US122M>
      </xsl:for-each>
    </imp1:US122M_Root-Element>
  </xsl:template>
</xsl:stylesheet>
