-- Declare package containing conversion functions between SQL and PL/SQL types
CREATE OR REPLACE PACKAGE BPEL_PURGEPARALLELDBADAPT1 AS
   PROCEDURE soa$delete_instances_in_paral (MIN_CREATION_DATE TIMESTAMP,
	MAX_CREATION_DATE TIMESTAMP,
	BATCH_SIZE INTEGER,
	MAX_RUNTIME INTEGER,
	RETENTION_PERIOD TIMESTAMP,
	DOP INTEGER,
	MAX_COUNT INTEGER,
	PURGE_PARTITIONED_COMPONENT INTEGER,
	COMPOSITE_NAME VARCHAR2,
	COMPOSITE_REVISION VARCHAR2,
	SOA_PARTITION_NAME VARCHAR2
	);
END BPEL_PURGEPARALLELDBADAPT1;
/
show errors
CREATE OR REPLACE PACKAGE BODY BPEL_PURGEPARALLELDBADAPT1 IS

   PROCEDURE soa$delete_instances_in_paral (MIN_CREATION_DATE TIMESTAMP,
	MAX_CREATION_DATE TIMESTAMP,
	BATCH_SIZE INTEGER,
	MAX_RUNTIME INTEGER,
	RETENTION_PERIOD TIMESTAMP,
	DOP INTEGER,
	MAX_COUNT INTEGER,
	PURGE_PARTITIONED_COMPONENT INTEGER,
	COMPOSITE_NAME VARCHAR2,
	COMPOSITE_REVISION VARCHAR2,
	SOA_PARTITION_NAME VARCHAR2
	) IS
 PURGE_PARTITIONED_COMPONENT_ BOOLEAN;
   BEGIN
 PURGE_PARTITIONED_COMPONENT_ := SYS.SQLJUTL.INT2BOOL(PURGE_PARTITIONED_COMPONENT);
      DEV_SOAINFRA.SOA.DELETE_INSTANCES_IN_PARALLEL(MIN_CREATION_DATE,
	MAX_CREATION_DATE,
	BATCH_SIZE,
	MAX_RUNTIME,
	RETENTION_PERIOD,
	DOP,
	MAX_COUNT,
	PURGE_PARTITIONED_COMPONENT_,
	COMPOSITE_NAME,
	COMPOSITE_REVISION,
	SOA_PARTITION_NAME
	);
   END soa$delete_instances_in_paral;

END BPEL_PURGEPARALLELDBADAPT1;
/
show errors
exit
