<?binding.jca ReadDB_db.jca?>
<wsdl:definitions name="ReadDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Misc/Project1/ReadDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Misc/Project1/ReadDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ReadDB">
    <plt:partnerLinkType name="ReadDB_plt">
        <plt:role name="ReadDB_role">
            <plt:portType name="tns:ReadDB_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ReadDB" schemaLocation="xsd/ReadDB_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="SlsTaxCltRptCollection_msg">
        <wsdl:part name="SlsTaxCltRptCollection" element="top:SlsTaxCltRptCollection"/>
    </wsdl:message>
    <wsdl:portType name="ReadDB_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:SlsTaxCltRptCollection_msg"/>
            <wsdl:output message="tns:SlsTaxCltRptCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
